"""Initial Migration

Revision ID: 7e39effd372d
Revises: 2296df3386de
Create Date: 2021-06-23 15:32:48.602550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e39effd372d'
down_revision = '2296df3386de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('profile_pic_path', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('pass_secure', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanics_email'), 'mechanics', ['email'], unique=True)
    op.create_index(op.f('ix_mechanics_specialization'), 'mechanics', ['specialization'], unique=False)
    op.create_index(op.f('ix_mechanics_username'), 'mechanics', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mechanics_username'), table_name='mechanics')
    op.drop_index(op.f('ix_mechanics_specialization'), table_name='mechanics')
    op.drop_index(op.f('ix_mechanics_email'), table_name='mechanics')
    op.drop_table('mechanics')
    # ### end Alembic commands ###
