"""migrate

Revision ID: 9def1c5d18e4
Revises: 4497ac391c4a
Create Date: 2021-06-25 00:16:47.761772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9def1c5d18e4'
down_revision = '4497ac391c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('displays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display', sa.String(), nullable=True),
    sa.Column('dispalyed_at', sa.DateTime(), nullable=True),
    sa.Column('dispalyed_by', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formfields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=True),
    sa.Column('time_posted', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dispalys')
    op.drop_table('formfilds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formfilds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('time_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='formfilds_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='formfilds_pkey')
    )
    op.create_table('dispalys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dispalyed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('dispalyed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='dispalys_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dispalys_pkey')
    )
    op.drop_table('formfields')
    op.drop_table('displays')
    # ### end Alembic commands ###
